version: '3.8'

services:
  single_service_app:
    container_name: single_service_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    networks:
      - app-network

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - '5432:5432'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge